- name: "Creating Windows Server(s) with existing parameters"
  hosts: localhost
  connection: local
  vars_prompt: 
    - name: "instances_number"
      prompt: "How many Windows instances would you like to create"
      private: yes
      default: 1
    - name: "resourcegroup_name"
      prompt: "What resource group do you want to launch the server(s) in"
      private: no
      default: "awx"
    - name: "vm_root_name"
      prompt: "Name of the vm root"
      private: no
      default: "new-vm"
    - name: "vm_size"
      prompt: "Size of the vm"
      private: no
      default: "Standard_B2s"
    - name: "managed_disk_type"
      prompt: "Type of the managed disk"
      private: no
      default: "Standard_LRS"
    - name: "admin_username"
      prompt: "Enter an admin username"
      private: no
      default: "Timi0"    
    - name: "virtualnetwork_name"
      prompt: "Enter the virtual network name"
      private: no
      default: "awx-vnet"
    - name: "securitygroup_name"
      prompt: "Enter the security group name"
      private: no
      default: "AWX-REDHAT-nsg"
    - name: "subnet_name"
      prompt: "Enter the subnet name"
      private: no
      default: "default"
    - name: "project_prefix"
      prompt: "Enter the project prefix"
      private: no
      default: "new"
  vars:
    - public_ip_name: "{{project_prefix}}-ip"
    - nic_root_name: "{{project_prefix}}-nic"
  tasks:
  - import_role:
      name: CreateCentOSWithExistingParameters
