--- #To create and attach a new Data disk to an existing Linux virtual machine
##Create and attach VM Disk
- name: "Attach Data disk to existing Linux VM"
  connection: local
  hosts: localhost
  tasks:
   - name: "Attaching Data disk to Linux VM"
     vars:
       rgname: undefined
       vmname: undefined
       disksizegb: undefined
     shell: az vm disk attach --resource-group "{{ rgname }}" --vm-name "{{ vmname }}" --disk "awxdisk1" --size-gb "{{ disksizegb }}" --sku Standard_LRS --new
