- name: Create managed disk
  azure_rm_managed_disk:
    name: "{{ diskname }}"
    location: centralus
    resource_group: "{{ rgname }}"
    disk_size_gb: "{{ disksizegb }}"
- name: Mount the managed disk to VM
  azure_rm_managed_disk:
    name: "{{ diskname }}"
    location: centralus
    resource_group: "{{ rgname }}"
    disk_size_gb: "{{ disksizegb }}"
    managed_by: "{{ vmname }}"
